#!/usr/bin/python
# -*- coding: UTF-8 -*-
__author__ = 'Roberto Valle'
__email__ = 'roberto.valle@upm.es'

from images_framework.src.categories import Name, Category as Oi


class Vehicle(Oi):
    Oi.VEHICLE.CAR = Name('Car')
    Oi.VEHICLE.BUS = Name('Bus')
    Oi.VEHICLE.PLANE = Name('Plane')
    Oi.VEHICLE.SHIP = Name('Ship')
    Oi.VEHICLE.HELICOPTER = Name('Helicopter')
    # COCO
    Oi.VEHICLE.BICYCLE = Name('Bicycle')
    Oi.VEHICLE.MOTORCYCLE = Name('Motorcycle')
    Oi.VEHICLE.AIRPLANE = Name('Airplane')
    Oi.VEHICLE.TRAIN = Name('Train')
    Oi.VEHICLE.BOAT = Name('Boat')
    # DOTA
    Oi.VEHICLE.LARGE_VEHICLE = Name('Large vehicle')
    Oi.VEHICLE.SMALL_VEHICLE = Name('Small vehicle')
    # Xview
    Oi.VEHICLE.FIXED_WING_AIRCRAFT = Name('Fixed wing aircraft')
    Oi.VEHICLE.FIXED_WING_AIRCRAFT.SMALL_AIRCRAFT = Name('Small aircraft')
    Oi.VEHICLE.FIXED_WING_AIRCRAFT.CARGO_PLANE = Name('Cargo plane')
    Oi.VEHICLE.PASSENGER_VEHICLE = Name('Passenger vehicle')
    Oi.VEHICLE.PASSENGER_VEHICLE.SMALL_CAR = Name('Small car')
    Oi.VEHICLE.PASSENGER_VEHICLE.BUS = Name('Bus')
    Oi.VEHICLE.TRUCK = Name('Truck')
    Oi.VEHICLE.TRUCK.PICKUP_TRUCK = Name('Pickup truck')
    Oi.VEHICLE.TRUCK.UTILITY_TRUCK = Name('Utility truck')
    Oi.VEHICLE.TRUCK.CARGO_TRUCK = Name('Cargo truck')
    Oi.VEHICLE.TRUCK.TRUCK_BOX = Name('Truck box')
    Oi.VEHICLE.TRUCK.TRUCK_TRACTOR = Name('Truck tractor')
    Oi.VEHICLE.TRUCK.TRAILER = Name('Trailer')
    Oi.VEHICLE.TRUCK.TRUCK_FLATBED = Name('Truck flatbed')
    Oi.VEHICLE.TRUCK.TRUCK_LIQUID = Name('Truck liquid')
    Oi.VEHICLE.ENGINEERING_VEHICLE = Name('Engineering vehicle')
    Oi.VEHICLE.ENGINEERING_VEHICLE.TOWER_CRANE = Name('Tower crane')
    Oi.VEHICLE.ENGINEERING_VEHICLE.CONTAINER_CRANE = Name('Container crane')
    Oi.VEHICLE.ENGINEERING_VEHICLE.REACH_STACKER = Name('Reach stacker')
    Oi.VEHICLE.ENGINEERING_VEHICLE.STRADDLE_CARRIER = Name('Straddle carrier')
    Oi.VEHICLE.ENGINEERING_VEHICLE.MOBILE_CRANE = Name('Mobile crane')
    Oi.VEHICLE.ENGINEERING_VEHICLE.DUMP_TRUCK = Name('Dump truck')
    Oi.VEHICLE.ENGINEERING_VEHICLE.HAUL_TRUCK = Name('Haul truck')
    Oi.VEHICLE.ENGINEERING_VEHICLE.SCRAPER_TRACTOR = Name('Scrapper/tractor')
    Oi.VEHICLE.ENGINEERING_VEHICLE.FRONT_LOADER = Name('Front loader')
    Oi.VEHICLE.ENGINEERING_VEHICLE.EXCAVATOR = Name('Excavator')
    Oi.VEHICLE.ENGINEERING_VEHICLE.CEMENT_MIXER = Name('Cement mixer')
    Oi.VEHICLE.ENGINEERING_VEHICLE.GROUND_GRADER = Name('Ground grader')
    Oi.VEHICLE.ENGINEERING_VEHICLE.CRANE_TRUCK = Name('Crane truck')
    Oi.VEHICLE.RAILWAY_VEHICLE = Name('Railway vehicle')
    Oi.VEHICLE.RAILWAY_VEHICLE.PASSENGER_CAR = Name('Passenger car')
    Oi.VEHICLE.RAILWAY_VEHICLE.CARGO_CAR = Name('Cargo car')
    Oi.VEHICLE.RAILWAY_VEHICLE.FLAT_CAR = Name('Flat car')
    Oi.VEHICLE.RAILWAY_VEHICLE.TANK_CAR = Name('Tank car')
    Oi.VEHICLE.RAILWAY_VEHICLE.LOCOMOTIVE = Name('Locomotive')
    Oi.VEHICLE.MARITIME_VESSEL = Name('Maritime vessel')
    Oi.VEHICLE.MARITIME_VESSEL.MOTORBOAT = Name('Motorboat')
    Oi.VEHICLE.MARITIME_VESSEL.SAILBOAT = Name('Sailboat')
    Oi.VEHICLE.MARITIME_VESSEL.TUGBOAT = Name('Tugboat')
    Oi.VEHICLE.MARITIME_VESSEL.BARGE = Name('Barge')
    Oi.VEHICLE.MARITIME_VESSEL.FISHING_VESSEL = Name('Fishing vessel')
    Oi.VEHICLE.MARITIME_VESSEL.FERRY = Name('Ferry')
    Oi.VEHICLE.MARITIME_VESSEL.YATCH = Name('Yatch')
    Oi.VEHICLE.MARITIME_VESSEL.CONTAINER_SHIP = Name('Container ship')
    Oi.VEHICLE.MARITIME_VESSEL.OIL_TANKER = Name('Oil tanker')
    Oi.VEHICLE.VEHICLE_LOT = Name('Vehicle lot')
